### ISSUE TITLE
Typo of "multicloud" on "about" page

### ISSUE THREAD

**Issue by maxluoXIII** [open-cloud-guide/website#13]
### Bug report

In the second paragraph after the quote, "multicloud" is misspelled as "multiclodu":

> As both the cloud and open source landscapes evolve, we saw a need for a guide to highlight important aspects of hybrid cloud and **multiclodu** development--and their corresponding open source services.

### Expected behavior

"multicloud" is spelled correctly.

### Steps to reproduce the problem

Going to the "about" page of the guide.

### version

Not exactly sure what software's version we're looking for, but it's probably not relevant for this issue (an explanation for future reference would be appreciated though).
```

```

**Comment by emilyannmitchell** [comment]
Thanks for finding that @maxluoXIII . Fixed!
